### ISSUE TITLE
import name

### ISSUE THREAD

**Issue by ghost** [zaynetro/vk-messages-bot#11]
┌─[mouse@sr] - [~/vk-messages-bot] - [2017-03-04 03:57:37]
└─[1] <git:(master 1228115✈) > ./run.sh reset-db
Traceback (most recent call last):
  File "src/main.py", line 7, in <module>
    from bot import Bot
  File "/home/mouse/vk-messages-bot/src/bot.py", line 5, in <module>
    from telegram import Updater, ParseMode, ReplyKeyboardHide, ReplyKeyboardMarkup
ImportError: cannot import name 'Updater'

**Comment by gpchelkin** [comment]
You forgot to install python module requirements prior to starting the bot. You need to run:
```
pip3 install -r requirements.txt
```
Or see updated README with details on default Ubuntu python installation.

**Comment by ghost** [comment]
ou... thx!
